### PR TITLE
--workspace command line fix

### PR DESCRIPTION
**Pull request by guidodizi**
Put one sentence summarizing the changes. If this pull request follows up on
or is otherwise related to already existing pull requests, link to them via
`!<other pull request number>`.

- Adding `nargs` metadata on `Configuration` class. This way we can pass workspaces from command line like so `--workspace workspace1 workspace2`.
- `nargs` is set to `*` since we can have 0..N workspaces added. [See python docs](https://docs.python.org/3/library/argparse.html#nargs) on `nargs` for args parser

Related to Issue #294

### CODE REVIEW

**Review by dkmiller — APPROVED** [review]

**Comment by dkmiller** [comment]
@guidodizi , you have a merge conflict

**Comment by guidodizi** [comment]
@dkmiller had old main 😅

**Comment by guidodizi** [comment]
@dkmiller is there a release pipeline in place? new shrike version will be automatically deployed to pypi?

**Comment by dkmiller** [comment]
@guidodizi , please [create a new release](https://github.com/Azure/shrike/releases/new) following the existing examples. That will trigger the CI which pushes to PyPI.

**Pull request merged**
