### PR TITLE
log some environment variables

### PR DESCRIPTION
**Pull request by thomasp-ms**
This PR just logs some DevOps environment variables. My goal is to determine whether they can be useful to improve the smart mode and make it more robust to commits "sneaking in" between a PR merge and the Prepare stage in a build.

### CODE REVIEW

**Review by haozhestat — CHANGES_REQUESTED** [review]
Could you bump the version number (and update the corresponding unit testing file) ?

**Review by dkmiller — CHANGES_REQUESTED** [review]
Suggestion: rather than merging in, then removing, this kind of extra logging information, why not update one of our internal builds to install shrike from your branch,

```
pip install git+https://github.com/Azure/shrike@thomas/add-debug-logging
```

you can then make a dummy PR on our internal repo, which will trigger the desired logging?

Context:

- ['pip install' From a Git Repository](https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/)
- [pip install from git repo branch](https://stackoverflow.com/a/20101940)

**Comment by thomasp-ms** [comment]
> Could you bump the version number (and update the corresponding unit testing file) ?

I'm not following you, @haozhestat . I bumped the version already, and what are you suggesting I do about the unit tests file?

**Comment by thomasp-ms** [comment]
> Suggestion: rather than merging in, then removing, this kind of extra logging information, why not update one of our internal builds to install shrike from your branch,
> 
> ```
> pip install git+https://github.com/Azure/shrike@thomas/add-debug-logging
> ```
> 
> you can then make a dummy PR on our internal repo, which will trigger the desired logging?
> 
> Context:
> 
> * ['pip install' From a Git Repository](https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/)
> * [pip install from git repo branch](https://stackoverflow.com/a/20101940)

I like this, I'll give it a try

**Pull request closed without merging**
